# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import my_auth.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.SmallIntegerField()),
                ('read', models.NullBooleanField()),
                ('write', models.NullBooleanField()),
                ('token', models.CharField(default=my_auth.models.randstr, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('address', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('pub_key', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='tokens',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_auth.User'),
        ),
    ]
