# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('number', models.CharField(max_length=10)),
                ('txid', models.CharField(max_length=80, primary_key=True, serialize=False)),
            ],
        ),
    ]
