# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0002_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='chain',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='pri_key1',
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='pri_key2',
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='pub_key1',
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='pub_key2',
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
    ]
