# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0004_list_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='pub_key1',
            field=models.CharField(blank=True, default=None, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='pub_key2',
            field=models.CharField(blank=True, default=None, max_length=180, null=True),
        ),
    ]
