# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0005_auto_20170516_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='exp_time',
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
    ]
