# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0006_bid_exp_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='exp_time',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
