# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0007_auto_20170523_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='product',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
